version: '3'
services:
  redis:
    image: redis
    container_name: hdt_redis_compose
    ports:
      - "6379:6379"
    networks:
      - fullstack_hdt_backend-network

  hdt_backend_compose:
    image: "hdt-backend:0.0.1"
    container_name: hdt_backend_compose
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=default,in-memory
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - fullstack_hdt_backend-network

  hdt_frontend_compose:
    image: "hdt-dashboard:0.0.1"
    container_name: hdt_frontend_compose
    ports:
      - "3000:3000"
    depends_on:
      - hdt_backend_compose 
    networks:
      - fullstack_hdt_backend-network

# networks:
#   fullstack_hdt_backend-network:
#     # external: true